= Overview

This repo provides a simple tool to query GitHub REST APIs using JavaScript (NodeJS)

[source]
----
npm install && node retros --from "2023-02-27" --to "2023-03-10"
----

Replace the date range with your own in the same format. It generates a report about all the contributions (PRs and Issues) made within an organization between the `from` and `to` dates. It saved the report in `report-retros-<from>-to-<to>.md` file after caching it in the `.cache` folder.

[source]
----
node retros --from "2023-02-27" --to "2023-03-10" --no-cache
----

The app caches responses on disk in `_cache` folder. If you want to get fresh data, just pass the `--no-cache` flag.

[source]
----
node authors --from 2023-03-10 --to 2023-03-17 --author <github-username>
----
The command above generates a report summarizing the number of PRs created a nd reviewed by a contributor. It saves the report in `report-authors-<username>-<from>-to-<to>.md` file after caching it in the `.cache` folder.

[source]
----
node authors --from 2023-03-10 --to 2023-03-17 --author <github-username> --no-cache
----
Use this command to get the fresh results (if you think they may have changed on GitHub for some reason).