= Overview

This repo provides a simple tool to query GitHub REST APIs using JavaScript (NodeJS)

== Prerequisites

1. Understand the concepts of getting started with https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api?apiVersion=2022-11-28&tool=javascript[GitHub REST API]
2. Follow these steps to https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token[create a personal access token]
3. Save the access token in an environment variable `GH_FG_TOKEN`

== Commands

[source]
----
npm install && node retros --from "2023-02-27" --to "2023-03-10" --user <organization-name>
----

This command generates a report about all the contributions (PRs and Issues) made within an organization provided by `--user` between `from` and `to` dates. It saves the report in `report-retros-<from>-to-<to>.md` file after caching. Use `yyyy-mm-dd` format for date.

[source]
----
node retros --from "2023-02-27" --to "2023-03-10" --user <organization-name> --no-cache
----

The app caches responses on disk in `.cache` folder. If you want to get fresh data, just pass the `--no-cache` flag.

[source]
----
node authors --from 2023-03-10 --to 2023-03-17 --author <github-username>
----
The command above generates a report summarizing the number of PRs created and reviewed by a contributor provided by `author`. It saves the report in `report-authors-<username>-<from>-to-<to>.md` file after caching.

[source]
----
node authors --from 2023-03-10 --to 2023-03-17 --author <github-username> --no-cache
----
Use this command to get fresh results.